@startuml
'https://plantuml.com/use-case-diagram

:Stuff:
:Leader:
:Audit Bot: as AB
:Operator:
:Auth Manage Server: as AMS

(Auth config repo) as ACR
(Auth Service <AWS>) as AS

Stuff --> ACR: edit
Leader --> ACR: audit
AB --> ACR: audit
AB --> ACR: validate
Operator --> ACR: accept merge

AMS <-- ACR: load config
AMS -up-> AS: update role config

Stuff <-up- AS: authenticate
@enduml